language: cpp

os:
  - linux
  - osx

script:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      export COMPILER_NAME=gcc CC=gcc-5 CXX=g++-5;
    fi
  - make test-all

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - g++-5

notifications:
  email: false
